package micapolos.zexy2.live

enum class Primitive {
  LOGGED,
  READONLY,
  INT_PLUS,
  INT_MINUS,
  INT_TIMES,
  INT_KEEP_ADDING,
  DOUBLE_PLUS,
  DOUBLE_MINUS,
  DOUBLE_TIMES,
  DOUBLE_KEEP_ADDING,
  PARALLEL,
  LOAD_IMAGE,
  SPRITE,
  LABEL,
  KEY_IS_PRESSED,
  KEY_PRESSED,
  KEY_RELEASED,
  MOUSE_POSITION_X,
  MOUSE_POSITION_Y,
  MOUSE_BUTTON_IS_PRESSED,
  MOUSE_BUTTON_PRESSED,
  IMAGE_WIDTH,
  IMAGE_HEIGHT,
  FONT_STRING_WIDTH
}